#!/bin/bash
# This script initiates a mysqldump inside the MySQL container using the OpenShift "oc" binary.
# Important: Ensure that you are backing up into a persistent volume.

#Ensure that the oc binary is in your path
oc version >> /dev/null 2>&1
if [ "$?" -gt "0" ] ; then
  printf "\nEnsure that the \"oc\" command is in your PATH"
  exit 1
fi

# read in source configuration file or read from ENV variables.
if [ -e "`dirname "$0"`/.openshift-mysql-backup.config" ] ; then
  echo Reading from configuration file.
  source "`dirname "$0"`/.openshift-mysql-backup.config"

else
  echo configuration file does not exist. read values from enviornment variables.
fi


# Ensure that all configuration variables exist.
if [ -n "${BACKUP_LOC}" -a -n "${MYSQL_DUMP_BIN}" -a -n "${OSE_API}" -a -n "${PROJECT_NAME}" -a -n "${POD_SELECTOR}" -a -n "${API_TOKEN}" ] ; then
    echo Validation of configuration variables passed..
else
    echo Missing configuration values. Bailing...
    exit 1
fi

# get the current time
CURRENT_TIME=$(date "+%Y.%m.%d-%H.%M.%S")

echo
echo Starting execution at: $CURRENT_TIME
echo Configuration information
echo ---------------------------------------
echo MySQL Backup location: $BACKUP_LOC
echo MysQL mysql dump binary: $MYSQL_DUMP_BIN
echo OpenShift project name: $PROJECT_NAME
echo OpenShift mysql pod: $POD_SELECTOR
echo OpenShift project API token: $API_TOKEN
echo ---------------------------------------
echo
echo Starting MySQL backup
echo ---------------------------------------
echo

# get the mysql pod name
DB_POD=$(oc --server=${OSE_API} --token=${API_TOKEN} -n ${PROJECT_NAME} get pods -l deploymentconfig=${POD_SELECTOR} --no-headers | awk '{print $1}')

# Create backup folder if it does not already exist
oc --insecure-skip-tls-verify=true --server=${OSE_API} --token=${API_TOKEN} -n ${PROJECT_NAME} exec ${DB_POD} -- /bin/bash -c "if [ ! -d $BACKUP_LOC ] ; then echo Creating backup directory ; mkdir -p ${BACKUP_LOC} ; ls -al ${BACKUP_LOC} ; fi"

# Dump all the databases
oc --insecure-skip-tls-verify=true --server=${OSE_API} --token=${API_TOKEN} -n ${PROJECT_NAME} exec ${DB_POD} -- ${MYSQL_DUMP_BIN} -u root --all-databases --result-file=${BACKUP_LOC}/full-backup.${CURRENT_TIME}.sql

echo MySQL backup completed.
echo
exit 0
